# Need python for node_module appmetrics/node-gyp
# Install the app dependencies in a full UBI Node docker image
# FROM registry.access.redhat.com/ubi8/nodejs-14:latest
FROM node:14

WORKDIR /app/
COPY . .

# Copy package.json and package-lock.json
# COPY package*.json ./

# Install app dependencies
RUN npm install --production

# Copy the dependencies into a Slim Node docker image
# FROM registry.access.redhat.com/ubi8/nodejs-14-minimal:latest
FROM node:14-alpine
WORKDIR /app/

# Install app dependencies
COPY --from=0 /app/ ./

ENV NODE_ENV production
ENV PORT 3002

EXPOSE 3002
CMD ["npm", "start"]
